# Generated by Django 2.1.5 on 2021-07-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cotent',
            new_name='content',
        ),
    ]
